# Generated by Django 3.2.14 on 2022-11-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0044_auto_20230907_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='unique_id',
            field=models.CharField(db_index=True, null=True, max_length=50, default='', help_text='Unique task ID in the project', verbose_name='unique id'),
        ),
    ]
